spring.application.name=toolsChallenge

#DATABASE
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:api-tools-challenge}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver
spring.hikari.connection-timeout=30000
spring.hikari.maximum-pool-size=10
spring.hikari.minimum-idle=2
spring.hikari.idle-timeout=600000

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#FLYWAY
flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true

#MESSAGES
spring.messages.basename=messages
spring.messages.encoding=UTF-8